### ISSUE TITLE
Bower install pulls old version

### ISSUE THREAD

**Issue by senften** [alonho/angular-plotly#15]
bower install angular-plotly

pulls old version (0.1.2)

**Comment by j2kenton** [comment]
Seems like this (0.1.2) **is** the newest version.

[Angular-Plotly Releases](https://github.com/alonho/angular-plotly/releases)

**Comment by alonho** [comment]
It's time for a version increment: 0.1.3 is ready.

**Comment by j2kenton** [comment]
Great - thanks :)

*Jonathan Kenton*
- web & app ninja
www.j2k.co.il <http://j2k.co.il/>
052-383-5022
