### ISSUE TITLE
Width changes on update

### ISSUE THREAD

**Issue by davidrhoderick** [alonho/angular-plotly#4]
I am building an app and I want the graph to be the full width of its parent element.  When I change the data values, the plot.ly element width resets to 700px.

**Comment by davidrhoderick** [comment]
This is fixed by adding `Plotly.Plots.resize(element);` after `Plotly.redraw(element);` in the `scope.$watch` on layout and data.  Can you please update the repo or allow me to make changes to it?

**Comment by Etheryte** [comment]
@davidrhoderick Thanks for writing the solution here for any future lookers. I've already made a pull request with that bugfix and some other improvements about two weeks ago, you can see the pull requests tab above.
It's unclear whether and when it will be merged by the original author though.

**Comment by alonho** [comment]
Sorry for not being responsive guys, for some reason I didn't get notifications for this repo.

**Comment by Etheryte** [comment]
Since 97092e1df95c378bdd01bd3b008fd49c84da8af5 was merged, this issue should be resolved and closed.
